name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types:
      - trigger-rest-automation-workflow
    
jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log event payload
      run: echo '${{ toJson(github.event.client_payload) }}'
